@host = http://localhost:5000/articles
@jwt = JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NDMyMDM4OTUsImlhdCI6MTU0MzIwMzU5NSwibmJmIjoxNTQzMjAzNTk1LCJpZGVudGl0eSI6M30.PcJ2cvjah2hhRc9xX_m5YYFjzCDol8AOcUIQy1cBwd4
GET {{host}}

###

GET {{host}}
Content-Type: application/json
Authorization: {{jwt}}

{
    "request-type": "listAll"
}

###

GET {{host}}
Content-Type: application/json

{
    "request-type": "findById",
    "id": 3
}

###

GET {{host}}
Content-Type: application/json

{
    "request-type": "search",
    "args": {
        "text": "texto 2"
    }
}

###

POST {{host}}
Content-Type: application/json

{
    "title": "sdlfjbhsdlhifb2222222",
    "text": "texto 2"
}


###

PUT {{host}}
Content-Type: application/json

{
    "id": 8,
    "title": "asdfaaaaaa",
    "text": "asdf2222"
}

###

DELETE {{host}}
Content-Type: application/json
Authorization: {{jwt}}

{
    "id": 16
}